//Firebase references
var myDataRef = new Firebase('https://barhop.firebase.com'); 

var listRef = barhopRef.child('lists')
var barhopRef = listRef.parent();

var myRoutesRef = listRef.child('myRoutes');
var listRef = myRoutesRef.parent();

var nameRef = myRoutesRef.child('name')
var myRoutesRef = nameRef.parent();

var locationRef = nameRef.child ('location')
var nameRef = locationRef.parent();

var latRef = locationRef.child('lat')
var locationRef = latRef.parent();

var lngRef = locationRef.child('lng')
var locationRef = lngRef.parent();








// Generate a reference to a new location with push
var newPushRef = listRef.push();

// Set some data to the generated location
newPushRef.set({user_id: 'wilma', text: 'Hello'});//CHANGE TO WHAT DATA TO PUSH HERE

// Get the name generated by push
var pushedName = newPushRef.name();



function makeRoute(ref) {
	var myRoute = [array, array, array]; //IMPORT ROUTE ARRAYS
	for (var i = 0; i < myRoute.length; i++) {
		ref.push (myRoute[i]);
	}
}

function getRoute(ref, cb) {
	ref.startAt().limit(3).once("child_added", function(snapshot) {
		cb(snapshot.val());
	});
}

function go() {
	var testRef = new Firebase("https://barhop.firebaseIO.com/")
	makeRoute(testRef);
	getList(testRef, function(val) {
		alert(val);
	});
}

//Reading List data
var listRef = new Firebase('https://barhop.firebaseIO.com/');
listRef.on('child_added', function(snapshot) {
  var msgData = snapshot.val();
  alert(msgData.user_id + ' says ' + msgData.text);
});

//Removing List data
var listRef = new Firebase('https://barhop.firebaseIO.com/');
var msgRef = listRef.push();
msgRef.set({user_id: 'wilma', text: 'Hello'}); //CHANGE TO WHAT DATA TO PUSH HERE

// Later ...
msgRef.remove();