//Firebase references
var barhopRef = new Firebase('https://barhop.firebase.com'); 

var myRoutesRef = barhopRef.child('myRoutes');
var barhopRef = myRoutesRef.parent


// Generate a reference to a new location with push
var newRouteRef = myRoutesRef.push();

// Set some data to the generated location
newRouteRef.set({name: 'Nattas rutt', location: [startP + ',' + transitP + ',' + endP]});

// Get the name generated by push
var pushedName = newRouteRef.name(name: 'Nattas rutt', location: [startP + ',' + transitP + ',' + endP]);

//Reading List data
var myRoutesRef = new Firebase('https://barhop.firebaseIO.com/myRoutes');
myRoutesRef.on('child_added', function(snapshot) {
  var msgData = snapshot.val();
  console.log("Route Added")
});

	
	









